=== Pedro44-henrique44/pos-2026-tarefas/tarefa05/imobiliaria.xsd
<xsi:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema"
        xmlns="http://imobiliaria.org"
        targetNamespace="http://imobiliaria.org"
        elementFormDefault="qualified">
    <xsi:element name="imobiliaria">
        <xsi:complexType>
            <xsi:sequence>
                <xsi:element name="imovel" minOccurs="1" maxOccurs="unbounded">
                    <xsi:complexType>
                        <xsi:sequence>
                            <xsi:element name="descricao" type="xsi:string"/>
                            
                            <xsi:element name="proprietario">
                                <xsi:complexType> <!-- utilizei o choice, somente para garantir que o proprietario tenha pelo menos 1 entre os dois-->
                                    <xsi:sequence>
                                        <xsi:element name="nome"/>
                                        <xsi:choice minOccurs="1" maxOccurs="unbounded">
                                            <xsi:element name="email" minOccurs="0"/>
                                            <xsi:element name="telefone" minOccurs="0"/>
                                        </xsi:choice>
                                    </xsi:sequence>
                                </xsi:complexType>

                            </xsi:element>

                            <xsi:element name="endereco">
                                <xsi:complexType>
                                    <xsi:sequence> <!--não entendi "que deve ser opcional" nas instrunções-->
                                        <xsi:element name="rua" minOccurs="0"/>
                                        <xsi:element name="bairro"  minOccurs="0"/>
                                        <xsi:element name="cidade"  minOccurs="0"/>
                                        <xsi:element name="numero"  minOccurs="0"/>
                                    </xsi:sequence>
                                </xsi:complexType>
                            </xsi:element>

                            <xsi:element name="caracteristicas">
                                <xsi:complexType>
                                    <xsi:sequence> <!-- invertido a sequencia (deveria ser tamanho, quarto, banheiro)-->
                                        <xsi:element name="numBanheiros" type="xsi:integer"/>
                                        <xsi:element name="numQuartos" type="xsi:integer"/>
                                        <xsi:element name="tamanho" type="xsi:decimal"/>
                                    </xsi:sequence>
                                </xsi:complexType>
                            </xsi:element>

                            <xsi:element name="valor" type="xsi:string"/>
                        </xsi:sequence>
                    <xsi:attribute name="ID" type="xsi:integer" use="required" />
                    </xsi:complexType>
                </xsi:element>
            </xsi:sequence>
        </xsi:complexType>

    </xsi:element>

</xsi:schema>

=== Pedro44-henrique44/pos-2026-tarefas/tarefa05/imobiliaria.xml
<?xml version="1.0" encoding="utf-8"?>
<imobiliaria xmlns="http://imobiliaria.org"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://imobiliaria.org imobiliaria.xsd">
    <imovel ID="01">
        <descricao>Casa simples com quintal</descricao>

        <proprietario>
            <nome>João Silva</nome>
            <email>JSemail@gmail.com</email><!--pelo menos um -->
            <telefone>83999990001</telefone><!-- pelo menos um -->
        </proprietario>

        <endereco>
            <rua>Rua das Flores</rua>
            <bairro>Centro</bairro>
            <cidade>Campina Grande</cidade>
            <numero>120</numero><!-- opcional e único, então a cardinalidade tem que ser 0 ou 1-->
        </endereco>

        <caracteristicas>
            <numBanheiros>1</numBanheiros>
            <numQuartos>2</numQuartos>
            <tamanho>80</tamanho>
        </caracteristicas>

        <valor>150000</valor>
    </imovel>

    <imovel ID="02">
        <descricao>Apartamento pequeno</descricao>

        <proprietario>
            <nome>Maria Souza</nome>
            <email>Marial@gmail.com</email><!--pelo menos um -->
            <telefone>83999990002</telefone><!-- pelo menos um -->
            <telefone>83999990012</telefone>
        </proprietario>

        <endereco>
            <rua>Rua João Pessoa</rua>
            <bairro>Prata</bairro>
            <cidade>Campina Grande</cidade>
            <numero>45</numero><!-- opcional e único, então a cardinalidade tem que ser 0 ou 1-->
        </endereco>

        <caracteristicas>
            <numBanheiros>1</numBanheiros>
            <numQuartos>1</numQuartos>
            <tamanho>50</tamanho>
        </caracteristicas>

        <valor>120000</valor>
    </imovel>

    <imovel ID="03">
        <descricao>Casa ampla com garagem</descricao>

        <proprietario>
            <nome>Carlos Pereira</nome>
            <telefone>8377770003</telefone><!-- pelo menos um -->
            <!-- sem email -->
        </proprietario>

        <endereco>
            <rua>Rua do Sol</rua>
            <bairro>Catolé</bairro>
            <cidade>Campina Grande</cidade>
            <numero>300</numero><!-- opcional e único, então a cardinalidade tem que ser 0 ou 1-->
        </endereco>

        <caracteristicas>
            <numBanheiros>2</numBanheiros>
            <numQuartos>3</numQuartos>
            <tamanho>120</tamanho>
        </caracteristicas>

        <valor>250000</valor>
    </imovel>


    <imovel ID="04">
        <descricao>Kitnet mobiliada</descricao>

        <proprietario>
            <nome>Ana Costa</nome>
            <telefone>8377770004</telefone><!-- pelo menos um -->
            <email>ana@gmail.com</email>
        </proprietario>

        <endereco>
            <rua>Rua da paz</rua>
            <bairro>Liberdade</bairro>
            <cidade>Campina Grande</cidade>
            <numero>78</numero>
        </endereco>

        <caracteristicas>
            <numBanheiros>1</numBanheiros>
            <numQuartos>1</numQuartos>
            <tamanho>35</tamanho>
        </caracteristicas>

        <valor>90000</valor>
    </imovel>

        <imovel ID="05">
        <descricao>Casa duplex moderna</descricao>

        <proprietario>
            <nome>Pedro Alves</nome>
            <telefone>8355550005</telefone><!-- pelo menos um -->
            <email>pedro@gmail.com</email>
        </proprietario>

        <endereco>
            <rua>Avenida Brasil</rua>
            <bairro>Alto Branco</bairro>
            <cidade>Campina Grande</cidade>
            <!-- ESSE IMOVEL NÃO TEM NUMERO (parte da atividade 05).
             da erro se o minOccurs="1"-->
        </endereco>

        <caracteristicas>
            <numBanheiros>3</numBanheiros>
            <numQuartos>4</numQuartos>
            <tamanho>185</tamanho>
        </caracteristicas>

        <valor>350000</valor>
    </imovel>

</imobiliaria>
