=== Pedro44-henrique44/pos-2026-tarefas/tarefa03/quiz.dtd
<!ELEMENT quiz (disciplina, professor, turma, data, questoes)> <!-- mudei "questões" para "questoes"-->
    <!ATTLIST quiz versao CDATA #REQUIRED>
    <!ELEMENT disciplina (#PCDATA)>
    <!ELEMENT professor (nome, matricula?)>
        <!ELEMENT nome (#PCDATA)>
        <!ELEMENT matricula (#PCDATA)> <!-- tirei o acento do i-->
    <!ELEMENT turma (#PCDATA)>
    <!ELEMENT data (#PCDATA)>
    <!ELEMENT questoes (questao+)>
        <!ELEMENT questao (enunciado, pontuaçao, alternativas)> <!-- tirei os acentos circunflexos-->
            <!ELEMENT enunciado (#PCDATA)>
            <!ELEMENT pontuaçao (#PCDATA)>
            <!ELEMENT alternativas (alternativa+)>
                <!ELEMENT alternativa (#PCDATA)>
                    <!ATTLIST alternativa correta (sim|nao) #REQUIRED>

=== Pedro44-henrique44/pos-2026-tarefas/tarefa03/quiz.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE quiz SYSTEM "quiz.dtd">
<quiz versao="1.0"><!-- a versão é demonstrativa -->
    <disciplina></disciplina>

    <professor>
        <nome></nome>
        <matricula></matricula>
    </professor>

    <turma></turma>

    <data></data>

    <questoes>
        <questao>
            <enunciado></enunciado>

            <pontuaçao></pontuaçao>

            <alternativas>
                <alternativa correta="sim"></alternativa>
            </alternativas>
        </questao>
    </questoes>
</quiz>
